# stylish-haskell configuration file
# ==================================
steps:
  - imports:
      align: file
  - language_pragmas:
      style: vertical
      remove_redundant: false
  - records: {}
  - trailing_whitespace: {}

columns: 90
